name: Deploy to S3

on:
  push:
    # Trigger this workflow only on commits with "[build]" in the commit message
    branches:
      - main
    # Filter commit messages to only run on "[build]" commit
    # You can modify the regular expression as needed
    paths:
      - "**/*"
    if: contains(github.event.head_commit.message, '[build]')

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Build React app
      run: |
        npm run build

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: |
        aws s3 sync ./build/ s3://$S3_BUCKET_NAME/ --delete --exclude "*.git/*" --acl public-read
